version: '2'
services:
  app:
    image: gogs/gogs:latest
    volumes:
      - /tmp/gogs-data:/data
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
  postgres:
    image: postgres:alpine
    volumes:
      - /tmp/gogs-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=gogs
